name: Unittest

on:
  push:
    paths:
      - 'core/**'
      - 'server/**'
      - 'tests/**'
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    paths:
      - 'core/**'
      - 'server/**'
      - 'tests/**'


jobs:
  # This workflow contains a single job called "build"
  build:
    name: Unittest AMD64 Ubuntu ${{ matrix.ubuntu }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [18.04]
    env:
      UBUNTU: ${{ matrix.ubuntu }}
    services:
      mysql:
        image: mysql:5.7.42
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: milvuscdc
        ports:
          - 3306:3306
      etcd:
        image: quay.io/coreos/etcd:v3.5.5
        env:
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
        ports:
          - 2379:2379
      kafka:
        image: apache/kafka:3.8.0
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
          - 9092:9092
      zookeeper:
        image: zookeeper:3.8
        env:
          ZOO_MY_ID: 1
          ZOO_SERVERS: server.1=zookeeper:2888:3888
        ports:
          - 2181:2181
#      pulsar:
#        image: apachepulsar/pulsar:2.8.2
#        ports:
#          - 6650:6650
#          - 8080:8080
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Apache Pulsar
        uses: reugn/github-action-pulsar@v1
        with:
          version: 2.8.2
      # Runs a single command using the runners shell
      - name: Run Unittest
        run: make test-go
      - name: Upload coverage to Codecov
        if: github.repository == 'zilliztech/milvus-cdc'
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.project.out
          name: ubuntu-${{ matrix.ubuntu }}-unittests